APP_NAME: "Current BTC vs USD Price Tracker"  #give your app a nice name
APP_REQUIREMENTS: #app requirements separated by a '-' on each new line. Requirements MUST be compatible with pyodide. Suggest specifying versions.
  - streamlit
  - requests
  - plotly
  - pandas
APP_ENTRYPOINT: app.py #entrypoint to app - change this to your main python file
CONFIG: false
APP_FILES:  #each file separated by a '-'. Can be .py files or other filetypes that will be converted to binary and embeded in the html.
  - assets/image.png #you can include non python files - they will be embedded in the html in binary format
